import React, { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import UploadPage from "@/pages/UploadPage";
import Tooltip from "@/ui/Tooltip";
import { useAuth } from "react-oidc-context";

import "./styles.css";

const UploadDialog = () => {
  const [isTooltip, setIsTooltip] = useState(false);
  const auth = useAuth();

  return (
    <Dialog.Root>
      <Dialog.Trigger asChild>
        <div
          style={{ position: "relative" }}
          onMouseEnter={() => setIsTooltip(true)}
          onMouseLeave={() => setIsTooltip(false)}
        >
          <button
            data-cy="preferences-btn"
            disabled={!auth?.isAuthenticated}
            id="preferences"
            className="buttonExcel"
          >
            Validate & Preview
          </button>
          {isTooltip && (
            <Tooltip show={isTooltip} isLoggedIn={!!auth?.isAuthenticated} />
          )}
        </div>
      </Dialog.Trigger>

      <Dialog.Portal>
        <Dialog.Overlay className="DialogOverlay" />
        <Dialog.Content className="DialogContent">
          <Dialog.Title className="DialogTitle">Upload Excel File</Dialog.Title>
          <Dialog.Description className="DialogDescription">
            Upload an Excel file generated by Template Designer to convert it to
            NeXus format.
            <br />
          </Dialog.Description>
          <UploadPage />
          <div
            style={{
              display: "flex",
              marginTop: 25,
              justifyContent: "flex-end",
            }}
          >
            <Dialog.Close asChild>
              <button data-cy="ok-btn" id="okBtn" className="Button">
                Cancel
              </button>
            </Dialog.Close>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
};

export default UploadDialog;
