---
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kerberizer"

  # Maintain dependencies for JS
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kerberizer"
    ignore:
      - dependency-name: "survey-core"
        versions: [">= 2.0.0"]
      - dependency-name: "survey-react-ui"
        versions: [">= 2.0.0"]
      - dependency-name: "react"
        versions: [">= 19.0.0"]
      - dependency-name: "react-dom"
        versions: [">= 19.0.0"]
      - dependency-name: "@types/react"
        versions: [">= 19.0.0"]
      - dependency-name: "@types/react-dom"
        versions: [">= 19.0.0"]
